remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console
title: boredcodebyk
author: boredcodebyk
description: Personal page

header_pages:
  - index.md

style: dark
listen_for_clients_preferred_style: true